name:                SingOut
version:             0.1.0.0
github:              "jbhayven/SingOut"
license:             BSD3
author:              "Przemysław Podleśny"
maintainer:          "p.podlesny@students.mimuw.edu.pl"
copyright:           "2021 Przemysław Podleśny"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jbhayven/SingOut#readme>

dependencies:
- base >= 4.7 && < 5
- Euterpea 
- mtl
- stm
- HSoM

library:
  source-dirs: src

executables:
  SingOut:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SingOut

tests:
  SingOut-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SingOut
